services:
  app:
    build: .
    container_name: imoveis-itajai
    ports:
      - "80:80"  # Frontend
      #- "3009:3000"  # Backend
    restart: always
    networks:
      imoveis_default:
       ipv4_address: 172.27.0.2

networks:
  imoveis_default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.0.0/16
          gateway: 172.27.0.1